

local def = {
	scoreRange = {
		[1] = {0, 60},
		[2] = {40, 70},
		[3] = {70, 160},
		[4] = {100, 200},
		[5] = {180, 800},
	},
	stampDist = {
		[1] = util.NormaliseWeightedList({
			{probability = 0.10, stamp = "money_stamp"},
			{probability = 0.05, stamp = "wild_stamp"},
			{probability = 0.01, stamp = "negative_stamp"},
			{probability = 0.08, stamp = "snake_stamp"},
			{probability = 0.15, stamp = "kangaroo_stamp"},
			{probability = 0.15, stamp = "emu_stamp"},
			{probability = 0.05, stamp = "bird_stamp"},
			{probability = 0.05, stamp = "tree_stamp"},
			{probability = 0.10, stamp = "rocket_stamp"},
			{probability = 0.05, stamp = "planet_stamp"},
			{probability = 0.05, stamp = "misprint_stamp"},
			{probability = 0.1, stamp = "blank_stamp"},
			
			{probability = 0.02, stamp = "renumber_stamp"},
			{probability = 0.02, stamp = "renumber_down_stamp"},
		}),
		[2] = util.NormaliseWeightedList({
			{probability = 2*0.10, stamp = "money_stamp"},
			{probability = 2*0.10, stamp = "wild_stamp"},
			{probability = 2*0.05, stamp = "pair_stamp"},
			{probability = 2*0.15, stamp = "kangaroo_stamp"},
			{probability = 2*0.15, stamp = "emu_stamp"},
			{probability = 2*0.05, stamp = "bird_stamp"},
			{probability = 2*0.05, stamp = "tree_stamp"},
			{probability = 2*0.10, stamp = "rocket_stamp"},
			{probability = 2*0.05, stamp = "planet_stamp"},
			{probability = 0.10, stamp = "snake_stamp"},
			{probability = 0.10, stamp = "bee_stamp"},
			{probability = 0.10, stamp = "flower_stamp"},
			{probability = 0.10, stamp = "sword_stamp"},
			{probability = 0.10, stamp = "bridge_stamp"},
			{probability = 0.05, stamp = "misprint_stamp"},
			{probability = 0.01, stamp = "clone_stamp"},
			{probability = 0.03, stamp = "sell_stamp"},
			{probability = 0.05, stamp = "renumber_stamp"},
			{probability = 0.05, stamp = "renumber_down_stamp"},
			{probability = 0.05, stamp = "paint_stamp"},
			{probability = 0.05, stamp = "quality_stamp"},
			{probability = 0.08, stamp = "blank_stamp"},
		}),
		[3] = util.NormaliseWeightedList({
			{probability = 2*0.10, stamp = "money_stamp"},
			{probability = 2*0.10, stamp = "wild_stamp"},
			{probability = 2*0.05, stamp = "pair_stamp"},
			{probability = 2*0.15, stamp = "kangaroo_stamp"},
			{probability = 2*0.15, stamp = "emu_stamp"},
			{probability = 2*0.05, stamp = "bird_stamp"},
			{probability = 2*0.05, stamp = "tree_stamp"},
			{probability = 2*0.10, stamp = "rocket_stamp"},
			{probability = 2*0.05, stamp = "planet_stamp"},
			{probability = 2*0.10, stamp = "snake_stamp"},
			{probability = 2*0.10, stamp = "bee_stamp"},
			{probability = 2*0.10, stamp = "flower_stamp"},
			{probability = 2*0.10, stamp = "sword_stamp"},
			{probability = 2*0.10, stamp = "bridge_stamp"},
			{probability = 0.1, stamp = "misprint_stamp"},
			{probability = 0.015, stamp = "clone_stamp"},
			{probability = 0.1, stamp = "sell_stamp"},
			{probability = 0.1, stamp = "renumber_stamp"},
			{probability = 0.1, stamp = "renumber_down_stamp"},
			{probability = 0.1, stamp = "paint_stamp"},
			{probability = 0.1, stamp = "quality_stamp"},
			{probability = 0.16, stamp = "blank_stamp"},
		}),
		[4] = util.NormaliseWeightedList({
			{probability = 3*0.10, stamp = "money_stamp"},
			{probability = 3*0.10, stamp = "wild_stamp"},
			{probability = 3*0.05, stamp = "pair_stamp"},
			{probability = 3*0.15, stamp = "kangaroo_stamp"},
			{probability = 3*0.15, stamp = "emu_stamp"},
			{probability = 3*0.05, stamp = "bird_stamp"},
			{probability = 3*0.05, stamp = "tree_stamp"},
			{probability = 3*0.10, stamp = "rocket_stamp"},
			{probability = 3*0.05, stamp = "planet_stamp"},
			{probability = 3*0.10, stamp = "snake_stamp"},
			{probability = 3*0.10, stamp = "bee_stamp"},
			{probability = 3*0.10, stamp = "flower_stamp"},
			{probability = 3*0.10, stamp = "sword_stamp"},
			{probability = 3*0.10, stamp = "bridge_stamp"},
			{probability = 3*0.10, stamp = "bridge_stamp"},
			{probability = 0.05, stamp = "huge_ne"},
			{probability = 0.05, stamp = "huge_nw"},
			{probability = 0.05, stamp = "huge_se"},
			{probability = 0.05, stamp = "huge_sw"},
			{probability = 0.1, stamp = "misprint_stamp"},
			{probability = 0.02, stamp = "clone_stamp"},
			{probability = 0.2, stamp = "sell_stamp"},
			{probability = 0.2, stamp = "renumber_stamp"},
			{probability = 0.2, stamp = "renumber_down_stamp"},
			{probability = 0.2, stamp = "paint_stamp"},
			{probability = 0.2, stamp = "quality_stamp"},
			{probability = 0.16, stamp = "blank_stamp"},
		}),
		[5] = util.NormaliseWeightedList({
			{probability = 3*0.10, stamp = "money_stamp"},
			{probability = 3*0.10, stamp = "wild_stamp"},
			{probability = 3*0.05, stamp = "pair_stamp"},
			{probability = 3*0.15, stamp = "kangaroo_stamp"},
			{probability = 3*0.15, stamp = "emu_stamp"},
			{probability = 3*0.05, stamp = "bird_stamp"},
			{probability = 3*0.05, stamp = "tree_stamp"},
			{probability = 3*0.10, stamp = "rocket_stamp"},
			{probability = 3*0.05, stamp = "planet_stamp"},
			{probability = 3*0.10, stamp = "snake_stamp"},
			{probability = 3*0.10, stamp = "bee_stamp"},
			{probability = 3*0.10, stamp = "flower_stamp"},
			{probability = 3*0.10, stamp = "sword_stamp"},
			{probability = 3*0.10, stamp = "bridge_stamp"},
			{probability = 3*0.10, stamp = "bridge_stamp"},
			{probability = 3*0.05, stamp = "huge_ne"},
			{probability = 3*0.05, stamp = "huge_nw"},
			{probability = 3*0.05, stamp = "huge_se"},
			{probability = 3*0.05, stamp = "huge_sw"},
			{probability = 0.1, stamp = "misprint_stamp"},
			{probability = 0.3, stamp = "clone_stamp"},
			{probability = 0.3, stamp = "sell_stamp"},
			{probability = 0.3, stamp = "renumber_stamp"},
			{probability = 0.3, stamp = "renumber_down_stamp"},
			{probability = 0.3, stamp = "paint_stamp"},
			{probability = 0.3, stamp = "quality_stamp"},
			{probability = 0.16, stamp = "blank_stamp"},
		}),
	},
}

return def
